services:
  mysql:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    env_file: .env   
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
